version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    depends_on:
      mongodb-primary:
        condition: service_healthy
      mongodb-secondary:
        condition: service_healthy
      mongodb-arbiter:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'

  mongodb-primary:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_ROOT_USER
      - MONGODB_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY
    volumes:
      - 'mongodata:/bitnami'
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 12

  mongodb-secondary:
    image: bitnami/mongodb:latest
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY
      - MONGODB_INITIAL_PRIMARY_ROOT_USER
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 12

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY
      - MONGODB_INITIAL_PRIMARY_ROOT_USER
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  mongodata:
    driver: local
