name: First Workflow # Name for the workflow
on: workflow_dispatch # Trigger the workflow manually
jobs:
  first-job: # Unique identifier for the job
    runs-on: ubuntu-latest # Specify the runner environment
    steps:
      - name: Print Greeting # Name of the step
        run: echo "Hello World!" # Command to execute

      - name: Print Goodbye
        run: echo "Goodbye World!"
